/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-07-31 01:10:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import beans.UserInfoBeans;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("beans.UserInfoBeans");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>トップ画面</title>\n");
      out.write("</head>\n");

	UserInfoBeans userInfoBeans = (UserInfoBeans) session.getAttribute("userInfoBeans");

      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./header/userHeader.jsp", out, false);
      out.write("\n");
      out.write("\t<div id=\"carousel-1\" class=\"carousel slide\">\n");
      out.write("\t\t<ol class=\"carousel-indicators\">\n");
      out.write("\t\t\t<li data-target=\"#carousel-1\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("\t\t\t<li data-target=\"#carousel-1\" data-slide-to=\"1\"></li>\n");
      out.write("\t\t\t<li data-target=\"#carousel-1\" data-slide-to=\"2\"></li>\n");
      out.write("\t\t</ol>\n");
      out.write("\t\t<div class=\"carousel-inner\">\n");
      out.write("\t\t\t<div class=\"carousel-item active\">\n");
      out.write("\t\t\t\t<a href=\"https://meitantei-pikachu.jp/\">\n");
      out.write("\t\t\t\t\t<img class=\"d-block w-50 mx-auto\" src=\"https://i.ytimg.com/vi/DGEme-q3D78/maxresdefault.jpg\" alt=\"First slide\">\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"carousel-item\">\n");
      out.write("\t\t\t\t<a href=\"https://www.disney.co.jp/movie/aladdin.html\">\n");
      out.write("\t\t\t\t\t<img class=\"d-block w-50 mx-auto\" src=\"https://i.ytimg.com/vi/U8pIQ4lJZ1c/maxresdefault.jpg\" alt=\"Second slide\">\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"carousel-item\">\n");
      out.write("\t\t\t\t<a href=\"http://shin-godzilla.jp/\">\n");
      out.write("\t\t\t\t\t<img class=\"d-block w-50 mx-auto\" src=\"https://moviework-orenchi.com/wp-content/uploads/2019/05/godzilla-1280x720.jpg\" alt=\"Third slide\">\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<a class=\"carousel-control-prev w-25 mx-auto\" href=\"#carousel-1\" role=\"button\" data-slide=\"prev\">\n");
      out.write("\t\t\t<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t\t<span class=\"sr-only\">Previous</span>\n");
      out.write("\t\t</a>\n");
      out.write("\t\t<a class=\"carousel-control-next w-25 mx-auto\" href=\"#carousel-1\" role=\"button\" data-slide=\"next\">\n");
      out.write("\t\t\t<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t\t<span class=\"sr-only\">Next</span>\n");
      out.write("\t\t</a>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"news w-50 my-5 mx-auto\">\n");
      out.write("\t\t<h4>新着情報</h4>\n");
      out.write("\t\t<ul class=\"list-group list-group-flush\">\n");
      out.write("\t\t\t<li class=\"list-group-item\">\n");
      out.write("\t\t\t\t<div class=\"news-date\">7月14日</div>\n");
      out.write("\t\t\t\t<div class=\"news-subject\">　名探偵ピカチュウ上映中！</div>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li class=\"list-group-item\">\n");
      out.write("\t\t\t\t\t<div class=\"news-date \">7月13日</div>\n");
      out.write("\t\t\t\t\t<div class=\"news-category\">　日本語字幕付き上映のご案内</div>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
